### ISSUE TITLE
Implement atomic writes and appends on the blockchain

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#123]
TODO:
- For writes: write to a temporary file, close it, move to where it should be
- For appends: copy file to a temporary file, append it, move to where it should be
- `FileSystemStorage` can perfectly incapsulate this logic

**Comment by dmugtasimov** [comment]
@andbortnik See https://pypi.org/project/atomicwrites/ or https://pypi.org/project/atomicfile/

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/249

**Comment by dmugtasimov** [comment]
@andbortnik please, address comments

**Comment by andbortnik** [comment]
@dmugtasimov Done

**Comment by dmugtasimov** [comment]
@andbortnik merged. Thank you. Please, reply to my comment in the PR.

**Comment by dmugtasimov** [comment]
```
ubuntu@ip-172-31-8-46:~$ docker ps -a
CONTAINER ID   IMAGE                                                                                      COMMAND                  CREATED          STATUS                      PORTS                                               NAMES
c5dc1eb5bf6f   nginx:1.19.10-alpine                                                                       "/docker-entrypoint.…"   12 minutes ago   Up 12 minutes               80/tcp, 0.0.0.0:8555->8555/tcp, :::8555->8555/tcp   ubuntu_reverse-proxy_1
271d2d7c4f34   docker.pkg.github.com/thenewboston-developers/thenewboston-node/thenewboston-node:latest   "./run.sh"               12 minutes ago   Exited (1) 12 minutes ago                                                       ubuntu_node_1
0f8447363d72   postgres:13.2-alpine                                                                       "docker-entrypoint.s…"   12 minutes ago   Up 12 minutes               5432/tcp                                            ubuntu_db_1
ubuntu@ip-172-31-8-46:~$ docker logs ubuntu_node_1
'thenewboston_node/project/settings/templates/nginx.conf' -> '/etc/nginx/conf.d/node.conf'
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.

165 static files copied to '/opt/project/thenewboston_node/project/staticfiles', 517 post-processed.
2021-07-10 15:15:39,934 INFO filelock Lock 140625291795808 acquired on /var/lib/blockchain/file.lock
2021-07-10 15:15:39,935 INFO filelock Lock 140625291795808 released on /var/lib/blockchain/file.lock
2021-07-10 15:15:39,936 INFO thenewboston_node.core.management.commands.start_node Empty blockchain detected: initializing with https://raw.githubusercontent.com/thenewboston-developers/Account-Backups/master/latest_backup/latest.json
2021-07-10 15:15:39,936 INFO root Reading account root file from https://raw.githubusercontent.com/thenewboston-developers/Account-Backups/master/latest_backup/latest.json
2021-07-10 15:15:40,106 INFO root DONE: Reading account root file from https://raw.githubusercontent.com/thenewboston-developers/Account-Backups/master/latest_backup/latest.json
2021-07-10 15:15:40,106 INFO root Converting
2021-07-10 15:15:40,107 INFO root DONE: Converting
2021-07-10 15:15:40,107 INFO root Writing result
2021-07-10 15:15:40,108 INFO filelock Lock 140625291795808 acquired on /var/lib/blockchain/file.lock
2021-07-10 15:15:40,182 ERROR thenewboston_node.core.logging Exception in PathOptimizedFileSystemStorage.save(...) after 11.773ms
Traceback (most recent call last):
  File "/opt/project/thenewboston_node/core/logging.py", line 70, in wrapper
    rv = callable_(*args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 80, in save
    self._persist(file_path, binary_data, 'wb', is_final=is_final)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 174, in _persist
    self._write_file(file_path, binary_data, mode)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 195, in _write_file
    fo.write(binary_data)
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/opt/project/thenewboston_node/core/utils/atomic_write.py", line 18, in atomic_write_append
    yield fo
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 169, in _open
    self.commit(f)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 204, in commit
    move_atomic(f.name, self._path)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 111, in move_atomic
    return _move_atomic(src, dst)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 59, in _move_atomic
    os.link(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmps6sao7by' -> '/var/lib/blockchain/blockchain-states/0/0/0/0/0/0/0/0/000000000.-arf.msgpack'
2021-07-10 15:15:40,184 INFO filelock Lock 140625291795808 released on /var/lib/blockchain/file.lock
2021-07-10 15:15:40,184 ERROR thenewboston_node.core.management.commands.start_node Could not get initial blockchain from https://raw.githubusercontent.com/thenewboston-developers/Account-Backups/master/latest_backup/latest.json (failing over to /opt/project/alpha-arf-latest.json)
Traceback (most recent call last):
  File "/opt/project/thenewboston_node/core/management/commands/start_node.py", line 21, in initialize_blockchain
    make_blockchain_state_from_account_root_file(source)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 55, in make_blockchain_state_from_account_root_file
    write_destination(blockchain_state, path=path)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 41, in write_destination
    write_default_blockchain(blockchain_state)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 28, in write_default_blockchain
    blockchain.add_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/core/utils/file_lock.py", line 15, in wrap
    return f(self, *args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/blockchain/file_blockchain.py", line 141, in add_blockchain_state
    return super().add_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/business_logic/blockchain/base/blockchain_state.py", line 41, in add_blockchain_state
    self.persist_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/core/utils/file_lock.py", line 34, in wrap
    return f(self, *args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/blockchain/file_blockchain.py", line 149, in persist_blockchain_state
    storage.save(file_path, blockchain_state.to_messagepack(), is_final=True)
  File "/opt/project/thenewboston_node/business_logic/storages/path_optimized_file_system.py", line 34, in save
    return super().save(self._get_optimized_path(file_path), binary_data, is_final=is_final)
  File "/opt/project/thenewboston_node/core/logging.py", line 70, in wrapper
    rv = callable_(*args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 80, in save
    self._persist(file_path, binary_data, 'wb', is_final=is_final)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 174, in _persist
    self._write_file(file_path, binary_data, mode)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 195, in _write_file
    fo.write(binary_data)
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/opt/project/thenewboston_node/core/utils/atomic_write.py", line 18, in atomic_write_append
    yield fo
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 169, in _open
    self.commit(f)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 204, in commit
    move_atomic(f.name, self._path)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 111, in move_atomic
    return _move_atomic(src, dst)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 59, in _move_atomic
    os.link(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmps6sao7by' -> '/var/lib/blockchain/blockchain-states/0/0/0/0/0/0/0/0/000000000.-arf.msgpack'
2021-07-10 15:15:40,185 INFO root Reading account root file from /opt/project/alpha-arf-latest.json
2021-07-10 15:15:40,186 INFO root DONE: Reading account root file from /opt/project/alpha-arf-latest.json
2021-07-10 15:15:40,187 INFO root Converting
2021-07-10 15:15:40,188 INFO root DONE: Converting
2021-07-10 15:15:40,188 INFO root Writing result
2021-07-10 15:15:40,188 INFO filelock Lock 140625291795808 acquired on /var/lib/blockchain/file.lock
2021-07-10 15:15:40,254 ERROR thenewboston_node.core.logging Exception in PathOptimizedFileSystemStorage.save(...) after 3.441ms
Traceback (most recent call last):
  File "/opt/project/thenewboston_node/core/management/commands/start_node.py", line 21, in initialize_blockchain
    make_blockchain_state_from_account_root_file(source)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 55, in make_blockchain_state_from_account_root_file
    write_destination(blockchain_state, path=path)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 41, in write_destination
    write_default_blockchain(blockchain_state)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 28, in write_default_blockchain
    blockchain.add_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/core/utils/file_lock.py", line 15, in wrap
    return f(self, *args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/blockchain/file_blockchain.py", line 141, in add_blockchain_state
    return super().add_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/business_logic/blockchain/base/blockchain_state.py", line 41, in add_blockchain_state
    self.persist_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/core/utils/file_lock.py", line 34, in wrap
    return f(self, *args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/blockchain/file_blockchain.py", line 149, in persist_blockchain_state
    storage.save(file_path, blockchain_state.to_messagepack(), is_final=True)
  File "/opt/project/thenewboston_node/business_logic/storages/path_optimized_file_system.py", line 34, in save
    return super().save(self._get_optimized_path(file_path), binary_data, is_final=is_final)
  File "/opt/project/thenewboston_node/core/logging.py", line 70, in wrapper
    rv = callable_(*args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 80, in save
    self._persist(file_path, binary_data, 'wb', is_final=is_final)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 174, in _persist
    self._write_file(file_path, binary_data, mode)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 195, in _write_file
    fo.write(binary_data)
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/opt/project/thenewboston_node/core/utils/atomic_write.py", line 18, in atomic_write_append
    yield fo
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 169, in _open
    self.commit(f)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 204, in commit
    move_atomic(f.name, self._path)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 111, in move_atomic
    return _move_atomic(src, dst)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 59, in _move_atomic
    os.link(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmps6sao7by' -> '/var/lib/blockchain/blockchain-states/0/0/0/0/0/0/0/0/000000000.-arf.msgpack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/project/thenewboston_node/core/logging.py", line 70, in wrapper
    rv = callable_(*args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 80, in save
    self._persist(file_path, binary_data, 'wb', is_final=is_final)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 174, in _persist
    self._write_file(file_path, binary_data, mode)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 195, in _write_file
    fo.write(binary_data)
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/opt/project/thenewboston_node/core/utils/atomic_write.py", line 18, in atomic_write_append
    yield fo
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 169, in _open
    self.commit(f)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 204, in commit
    move_atomic(f.name, self._path)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 111, in move_atomic
    return _move_atomic(src, dst)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 59, in _move_atomic
    os.link(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpnisl0dgg' -> '/var/lib/blockchain/blockchain-states/0/0/0/0/0/0/0/0/000000000.-arf.msgpack'
2021-07-10 15:15:40,255 INFO filelock Lock 140625291795808 released on /var/lib/blockchain/file.lock
Traceback (most recent call last):
  File "/opt/project/thenewboston_node/core/management/commands/start_node.py", line 21, in initialize_blockchain
    make_blockchain_state_from_account_root_file(source)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 55, in make_blockchain_state_from_account_root_file
    write_destination(blockchain_state, path=path)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 41, in write_destination
    write_default_blockchain(blockchain_state)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 28, in write_default_blockchain
    blockchain.add_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/core/utils/file_lock.py", line 15, in wrap
    return f(self, *args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/blockchain/file_blockchain.py", line 141, in add_blockchain_state
    return super().add_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/business_logic/blockchain/base/blockchain_state.py", line 41, in add_blockchain_state
    self.persist_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/core/utils/file_lock.py", line 34, in wrap
    return f(self, *args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/blockchain/file_blockchain.py", line 149, in persist_blockchain_state
    storage.save(file_path, blockchain_state.to_messagepack(), is_final=True)
  File "/opt/project/thenewboston_node/business_logic/storages/path_optimized_file_system.py", line 34, in save
    return super().save(self._get_optimized_path(file_path), binary_data, is_final=is_final)
  File "/opt/project/thenewboston_node/core/logging.py", line 70, in wrapper
    rv = callable_(*args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 80, in save
    self._persist(file_path, binary_data, 'wb', is_final=is_final)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 174, in _persist
    self._write_file(file_path, binary_data, mode)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 195, in _write_file
    fo.write(binary_data)
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/opt/project/thenewboston_node/core/utils/atomic_write.py", line 18, in atomic_write_append
    yield fo
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 169, in _open
    self.commit(f)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 204, in commit
    move_atomic(f.name, self._path)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 111, in move_atomic
    return _move_atomic(src, dst)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 59, in _move_atomic
    os.link(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmps6sao7by' -> '/var/lib/blockchain/blockchain-states/0/0/0/0/0/0/0/0/000000000.-arf.msgpack'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/project/thenewboston_node/manage.py", line 22, in <module>
    main()
  File "/opt/project/thenewboston_node/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/project/thenewboston_node/core/management/commands/start_node.py", line 86, in handle
    initialize_blockchain(
  File "/opt/project/thenewboston_node/core/management/commands/start_node.py", line 25, in initialize_blockchain
    make_blockchain_state_from_account_root_file(failover_source)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 55, in make_blockchain_state_from_account_root_file
    write_destination(blockchain_state, path=path)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 41, in write_destination
    write_default_blockchain(blockchain_state)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain_state.py", line 28, in write_default_blockchain
    blockchain.add_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/core/utils/file_lock.py", line 15, in wrap
    return f(self, *args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/blockchain/file_blockchain.py", line 141, in add_blockchain_state
    return super().add_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/business_logic/blockchain/base/blockchain_state.py", line 41, in add_blockchain_state
    self.persist_blockchain_state(blockchain_state)
  File "/opt/project/thenewboston_node/core/utils/file_lock.py", line 34, in wrap
    return f(self, *args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/blockchain/file_blockchain.py", line 149, in persist_blockchain_state
    storage.save(file_path, blockchain_state.to_messagepack(), is_final=True)
  File "/opt/project/thenewboston_node/business_logic/storages/path_optimized_file_system.py", line 34, in save
    return super().save(self._get_optimized_path(file_path), binary_data, is_final=is_final)
  File "/opt/project/thenewboston_node/core/logging.py", line 70, in wrapper
    rv = callable_(*args, **kwargs)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 80, in save
    self._persist(file_path, binary_data, 'wb', is_final=is_final)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 174, in _persist
    self._write_file(file_path, binary_data, mode)
  File "/opt/project/thenewboston_node/business_logic/storages/file_system.py", line 195, in _write_file
    fo.write(binary_data)
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/opt/project/thenewboston_node/core/utils/atomic_write.py", line 18, in atomic_write_append
    yield fo
  File "/usr/local/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 169, in _open
    self.commit(f)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 204, in commit
    move_atomic(f.name, self._path)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 111, in move_atomic
    return _move_atomic(src, dst)
  File "/root/.cache/pypoetry/virtualenvs/thenewboston-node-gHi8t1rX-py3.9/lib/python3.9/site-packages/atomicwrites/__init__.py", line 59, in _move_atomic
    os.link(src, dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmpnisl0dgg' -> '/var/lib/blockchain/blockchain-states/0/0/0/0/0/0/0/0/000000000.-arf.msgpack'
```

**Comment by dmugtasimov** [comment]
@andbortnik Looks like you broke something. See prev. comment

**Comment by andbortnik** [comment]
@dmugtasimov Please review https://github.com/thenewboston-developers/thenewboston-node/pull/263

**Comment by dmugtasimov** [comment]
@andbortnik thank you, merged
