### ISSUE TITLE
Fix `make dev-initialize-blockchain`

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#390]
```
dmugtasimov@dmugtasimov-Latitude-E5550 ~/gitrep/thenewboston/thenewboston-node $ make dev-initialize-blockchain
poetry run python -m thenewboston_node.manage initialize_blockchain -f https://raw.githubusercontent.com/thenewboston-developers/Account-Backups/master/latest_backup/latest.json
Traceback (most recent call last):
  File "/home/dmugtasimov/.pyenv/versions/3.9.2/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dmugtasimov/.pyenv/versions/3.9.2/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/manage.py", line 22, in <module>
    main()
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/dmugtasimov/.virtualenvs/thenewboston-node-BkWiXaKK-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/dmugtasimov/.virtualenvs/thenewboston-node-BkWiXaKK-py3.9/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dmugtasimov/.virtualenvs/thenewboston-node-BkWiXaKK-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dmugtasimov/.virtualenvs/thenewboston-node-BkWiXaKK-py3.9/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/core/management/commands/initialize_blockchain.py", line 75, in handle
    if not blockchain.is_empty() and options['force']:
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/blockchain/base/__init__.py", line 55, in is_empty
    return not (self.has_blockchain_states() or self.has_blocks())
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/blockchain/base/blockchain_state.py", line 67, in has_blockchain_states
    return any(self.yield_blockchain_states())
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/blockchain/file_blockchain/blockchain_state.py", line 114, in yield_blockchain_states
    yield from self._yield_blockchain_states(1, lazy=lazy)
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/blockchain/file_blockchain/blockchain_state.py", line 109, in _yield_blockchain_states
    yield self._load_blockchain_state(file_path)
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/blockchain/file_blockchain/blockchain_state.py", line 80, in _load_blockchain_state
    blockchain_state = BlockchainState.from_messagepack(storage.load(file_path))
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/models/mixins/compactable.py", line 155, in from_messagepack
    return cls.from_compact_dict(unpacked, compact_keys=compact_keys, compact_values=compact_values)
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/models/mixins/compactable.py", line 110, in from_compact_dict
    dict_ = cls.from_compact_values(dict_)
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/models/mixins/compactable.py", line 130, in from_compact_values
    return cls._transform_dict(dict_, transform_map=get_type_uncompact_transform_map())
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/models/mixins/compactable.py", line 134, in _transform_dict
    field_types = cls.get_field_types(dict_)
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/models/mixins/compactable.py", line 147, in get_field_types
    return {field_name: cls.get_field_type(field_name) for field_name in dict_}
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/models/mixins/compactable.py", line 147, in <dictcomp>
    return {field_name: cls.get_field_type(field_name) for field_name in dict_}
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/models/mixins/base.py", line 28, in get_field_type
    type_ = cls.get_field(field_name).type
  File "/home/dmugtasimov/gitrep/thenewboston/thenewboston-node/thenewboston_node/business_logic/models/mixins/base.py", line 20, in get_field
    return cls.get_fields()[field_name]
KeyError: 'account_states'
Makefile:69: recipe for target 'dev-initialize-blockchain' failed
make: *** [dev-initialize-blockchain] Error 1
```

**Comment by dmugtasimov** [comment]
@fonar @andbortnik whoever picks it first, please, unassign another. I guess this is a regression with making blockchain state signable.

**Comment by andbortnik** [comment]
@dmugtasimov The issue is we changed the format of blockchain state files. And locally stored files are now in the obsolete format. 

There are 2 options:
1. We drop the blockchain and reinitialize it again from the source.
2. We implement migrations which are run on deployment. To do that we'll have to maintain several versions of models in order to be able to read the old format and to write the new one.

@dmugtasimov What do you think?

**Comment by dmugtasimov** [comment]
@andbortnik we do not have to maintain backward compatibility at the moment. if the issue is about having files remained from previous run then just delete the files and run the command again.

@fonar please, confirm that the issue is identified correctly.

Please, let me know if need just close this issue
