### ISSUE TITLE
Synchronize blockchain on the first start after node deployment

### ISSUE THREAD

**Issue by dmugtasimov** [thenewboston-developers/thenewboston-node#417]

**Comment by dmugtasimov** [comment]
implemented here: https://github.com/thenewboston-developers/thenewboston-node/pull/422

**Comment by dmugtasimov** [comment]
Having issue:

```
2021-09-25 16:14:04,355 WARNING thenewboston_node.core.management.commands.sync_blockchain Could not synchronize blockchain with b8591396e291372070db2c3e57c66e8c28401856e8adf2e53c707f7c9c325dac at http://3.143.205.184:8555/
Traceback (most recent call last):
  File "/opt/project/thenewboston_node/core/management/commands/sync_blockchain.py", line 36, in handle
    sync_minimal_to_file_blockchain(source, blockchain)
  File "/opt/project/thenewboston_node/business_logic/utils/blockchain.py", line 184, in sync_minimal_to_file_blockchain
    os.rename(target_base_directory, throw_away_blockchain_directory)
OSError: [Errno 16] Device or resource busy: '/var/lib/blockchain' -> '/var/lib/blockchain.163258644409428.163258644435526'
2021-09-25 16:14:04,359 ERROR thenewboston_node.core.management.commands.sync_blockchain Could not synchronize blockchain with the network
```

**Comment by dmugtasimov** [comment]
fix: https://github.com/thenewboston-developers/thenewboston-node/pull/429

**Comment by dmugtasimov** [comment]
Synchronization is successful, but not is not operational because https://github.com/thenewboston-developers/thenewboston-node/issues/428 is not done yet.

```
root@ubuntu-s-1vcpu-1gb-nyc1-01:~# bash <(wget -qO- https://raw.githubusercontent.com/thenewboston-developers/thenewboston-node/master/scripts/deploy.sh)

Redirecting output to ‘wget-log.1’.
Removing login credentials for docker.pkg.github.com
Interactive docker registry login (username=github username; password=github personal access token (not github password)
Username: dmugtasimov
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
--2021-09-25 17:13:25--  https://raw.githubusercontent.com/thenewboston-developers/thenewboston-node/master/docker-compose.yml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1218 (1.2K) [text/plain]
Saving to: ‘docker-compose.yml’

docker-compose.yml                               100%[=========================================================================================================>]   1.19K  --.-KB/s    in 0s      

2021-09-25 17:13:25 (46.7 MB/s) - ‘docker-compose.yml’ saved [1218/1218]

Pulling db            ... done
Pulling node          ... done
Pulling reverse-proxy ... done
Running migrations...
Creating root_node_run ... done
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
Initializing blockchain...
Creating root_node_run ... done
2021-09-25 17:13:55,722 INFO root Reading blockchain state from /opt/project/blockchain-state.msgpack.xz
2021-09-25 17:13:55,773 INFO root DONE: Reading blockchain state from /opt/project/blockchain-state.msgpack.xz
2021-09-25 17:13:55,775 INFO root Adding the blockchain state
2021-09-25 17:13:55,930 INFO root DONE: Adding the blockchain state
Synchronizing blockchain...
Creating root_node_run ... done
Successfully synchronized blockchain with http://3.143.205.184:8555/
Recreating root_db_1 ... done
Creating root_node_1 ... done
Creating root_reverse-proxy_1 ... done
Removing login credentials for docker.pkg.github.com
Node has not started yet, waiting 5 seconds for retry (1)
Node has not started yet, waiting 5 seconds for retry (2)
Node has not started yet, waiting 5 seconds for retry (3)
Node has not started yet, waiting 5 seconds for retry (4)
Node has not started yet, waiting 5 seconds for retry (5)
Node has not started yet, waiting 5 seconds for retry (6)
Node has not started yet, waiting 5 seconds for retry (7)
Node has not started yet, waiting 5 seconds for retry (8)
Node has not started yet, waiting 5 seconds for retry (9)
Node has not started yet, waiting 5 seconds for retry (10)
Node has not started yet, waiting 5 seconds for retry (11)
Unable to start node.
Stopping root_reverse-proxy_1 ... done
Stopping root_node_1          ... done
Stopping root_db_1            ... done
Removing root_reverse-proxy_1 ... done
Removing root_node_1          ... done
Removing root_db_1            ... done
Removing network root_default
```

**Comment by dmugtasimov** [comment]
considering the task as done
